# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-04 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myverokey',
            name='verokey',
            field=models.CharField(blank=True, max_length=110),
        ),
    ]
